# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BhagavadGeeta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BhagavadGeeta
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'
  pod 'SwiftKeychainWrapper'
  pod 'MotionToastView'

end
